mysql:
  addr: 127.0.0.1:3306
  username: ryujin
  password: LCSZBD20030208lc!
  database: fastgo
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s

log:
  caller-enabled: true
  stacktrace-enabled: true
  level: debug
  format: json
  output: 
    - stdout

http:
  addr: 127.0.0.1:8080

grpc:
  addr: 127.0.0.1:6666

# 服务模式，可选值为 http、grpc、grpc-gateway
server-mode: http
# JWT 签发密钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
# JWT Token 过期时间
expiration: 1000h
