mysql:
  addr: 127.0.0.1:3306
  username: ryujin
  password: LCSZBD20030208lc!
  database: fastgo
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s

log:
  level: info
  format: text
  output: stdout

addr: ":8080"

# JWT 签发密钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
# JWT Token 过期时间
expiration: 1000h
