// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.1
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastBlog_Healthz_FullMethodName = "/v1.FastBlog/Healthz"
)

// FastBlogClient is the client API for FastBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FastBlog 定义了一个 FastBlog RPC 服务
type FastBlogClient interface {
	// Healthz 健康检查
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type fastBlogClient struct {
	cc grpc.ClientConnInterface
}

func NewFastBlogClient(cc grpc.ClientConnInterface) FastBlogClient {
	return &fastBlogClient{cc}
}

func (c *fastBlogClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, FastBlog_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastBlogServer is the server API for FastBlog service.
// All implementations must embed UnimplementedFastBlogServer
// for forward compatibility.
//
// FastBlog 定义了一个 FastBlog RPC 服务
type FastBlogServer interface {
	// Healthz 健康检查
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	mustEmbedUnimplementedFastBlogServer()
}

// UnimplementedFastBlogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastBlogServer struct{}

func (UnimplementedFastBlogServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedFastBlogServer) mustEmbedUnimplementedFastBlogServer() {}
func (UnimplementedFastBlogServer) testEmbeddedByValue()                  {}

// UnsafeFastBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastBlogServer will
// result in compilation errors.
type UnsafeFastBlogServer interface {
	mustEmbedUnimplementedFastBlogServer()
}

func RegisterFastBlogServer(s grpc.ServiceRegistrar, srv FastBlogServer) {
	// If the following call pancis, it indicates UnimplementedFastBlogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastBlog_ServiceDesc, srv)
}

func _FastBlog_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastBlogServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastBlog_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastBlogServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FastBlog_ServiceDesc is the grpc.ServiceDesc for FastBlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastBlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FastBlog",
	HandlerType: (*FastBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _FastBlog_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/v1/apiserver.proto",
}
